name: Test Pipeline

on: [push]

jobs:
  Explore_Github_Actions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker compose up -d
    - run: docker tag mlops-ml_model anthonybelval/mlops-ml_model:latest
    - run: docker login -u anthonybelval -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push mlops-ml_model:latest
    - run: sshpass -p Supermotdepasse!42 ssh ubuntu@20.86.55.5 
    - run: docker pull mlops-ml_model
    - run: docker run mlops-ml_model