name: Test Pipeline

on: [push]

jobs:
  Explore_Github_Actions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker compose up -d
    - run: docker tag mlops-ml_model anthonybelval/mlops-ml_model:latest
    - run: docker login -u anthonybelval -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push anthonybelval/mlops-ml_model:latest
    - run: sshpass -p Supermotdepasse!42 ssh -o "StrictHostKeyChecking=no" ubuntu@20.86.55.5 "docker stop anthony || true && docker pull anthonybelval/mlops-ml_model && docker run --name anthony -d -p 5023:8080 anthonybelval/mlops-ml_model"